version: "3"

networks:
  default:
    external: false

services:
  pgsql15:
    image: postgres:15
    container_name: pgsql15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=oduser
      - POSTGRES_PASSWORD=od_pwd
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
  odoo17:
    image: odoo:17
    container_name: odoo17
    depends_on:
      - pgsql15
    volumes:
      - ../:/mnt/extra-addons
    environment:
      - ODOO_RC=/mnt/extra-addons/odoo.conf
      - HOST=pgsql15
      - USER=oduser
      - PASSWORD=od_pwd
    ports:
      - 8769:8069
      - 8772:8072

volumes:
  odoo-web-data:
  odoo-db-data: